name: Preview Deployment

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ionos
    env: 
      ASTRO_CONFIG: ${{ secrets.ASTRO_CONFIG }}
      ASTRO_BASE_PATH: ${GITHUB_BASE_REF##*/}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: List dir
        run: |
          pwd
          ls -la
      - name: Replace config file
        run: echo "$ASTRO_CONFIG" > astro.config.mjs
      # - name: Variable substitution
      #   run: sed -i "s/REPLACEME/${GITHUB_BASE_REF##*/}/" astro.config.mjs
      - name: Install dependencies
        run: npm ci
      - name: Build site
        run: npm run build
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: deployment
          retention-days: 5
          path: |
            ./
            !node_modules

  deploy:
    needs: build
    environment: ionos
    runs-on: ubuntu-latest
    env:
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      SFTP_HOST: ${{ secrets.SFTP_HOST }}
      SFTP_USER: ${{ secrets.SFTP_USER }}
      SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: github-pages
      - name: Extract artifact
        run: |
          mkdir ${GITHUB_BASE_REF##*/}
          tar -xvf artifact.tar -C ${GITHUB_BASE_REF##*/}
      - name: Install LFTP
        run: sudo apt-get install -y lftp
      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
      - name: List dir
        run: |
          pwd
          ls -la
      - name: Deploy via LFTP to SFTP target
        run: lftp -e "set ftp:list-options -a; set net:timeout 5; set net:max-retries 3; set net:reconnect-interval-base 5; open sftp://$SFTP_HOST; user $SFTP_USER $SFTP_PASSWORD; mirror --reverse --delete ./${GITHUB_BASE_REF##*/}; bye"
